// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "recomeristem_types.hpp"
#include <Rcpp.h>

using namespace Rcpp;

// getParameters_from_files
List getParameters_from_files(Rcpp::String folder);
RcppExport SEXP recomeristem_getParameters_from_files(SEXP folderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type folder(folderSEXP);
    rcpp_result_gen = Rcpp::wrap(getParameters_from_files(folder));
    return rcpp_result_gen;
END_RCPP
}
// getMeteo_from_files
List getMeteo_from_files(Rcpp::String folder);
RcppExport SEXP recomeristem_getMeteo_from_files(SEXP folderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type folder(folderSEXP);
    rcpp_result_gen = Rcpp::wrap(getMeteo_from_files(folder));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_run_from_dataframe
List rcpp_run_from_dataframe(List dfParameters, List dfMeteo);
RcppExport SEXP recomeristem_rcpp_run_from_dataframe(SEXP dfParametersSEXP, SEXP dfMeteoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dfParameters(dfParametersSEXP);
    Rcpp::traits::input_parameter< List >::type dfMeteo(dfMeteoSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_run_from_dataframe(dfParameters, dfMeteo));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_vObs
List rcpp_get_vObs(Rcpp::String vObsPath);
RcppExport SEXP recomeristem_rcpp_get_vObs(SEXP vObsPathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type vObsPath(vObsPathSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_vObs(vObsPath));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_reduceVobs
List rcpp_reduceVobs(List vObs, List results);
RcppExport SEXP recomeristem_rcpp_reduceVobs(SEXP vObsSEXP, SEXP resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type vObs(vObsSEXP);
    Rcpp::traits::input_parameter< List >::type results(resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_reduceVobs(vObs, results));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_reduceResults
List rcpp_reduceResults(List results, List vobs);
RcppExport SEXP recomeristem_rcpp_reduceResults(SEXP resultsSEXP, SEXP vobsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type results(resultsSEXP);
    Rcpp::traits::input_parameter< List >::type vobs(vobsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_reduceResults(results, vobs));
    return rcpp_result_gen;
END_RCPP
}
