# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getParameters_from_files <- function(folder) {
    .Call('recomeristem_getParameters_from_files', PACKAGE = 'recomeristem', folder)
}

getMeteo_from_files <- function(folder) {
    .Call('recomeristem_getMeteo_from_files', PACKAGE = 'recomeristem', folder)
}

rcpp_run_from_dataframe <- function(dfParameters, dfMeteo) {
    .Call('recomeristem_rcpp_run_from_dataframe', PACKAGE = 'recomeristem', dfParameters, dfMeteo)
}

rcpp_get_vObs <- function(vObsPath) {
    .Call('recomeristem_rcpp_get_vObs', PACKAGE = 'recomeristem', vObsPath)
}

rcpp_reduceVobs <- function(vObs, results) {
    .Call('recomeristem_rcpp_reduceVobs', PACKAGE = 'recomeristem', vObs, results)
}

rcpp_reduceResults <- function(results, vobs) {
    .Call('recomeristem_rcpp_reduceResults', PACKAGE = 'recomeristem', results, vobs)
}

